# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.IntegerField()),
                ('sponsors', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='sponsor',
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('T&L', 'T&L'), ('CPG', 'CPG'), ('Field', 'Field')], max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('vsCntrl', 'vsCntrl'), ('Sales', 'Sales')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wavedate',
            name='pre_start',
            field=models.DateField(verbose_name='Pre Period Start Date'),
        ),
    ]
