# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0005_auto_20160214_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='wave_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
